server:
  port: 8090
spring:
  application:
    name: consultorios-medicos
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER      
  main:
    allow-circular-references: true
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect